{
 "title": "Sprint 3 project",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Number of Requests in Progress",
   "type": "stat",
   "description": "Number of requests currently in progress",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "inprogress_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Median Prediction",
   "type": "timeseries",
   "description": "Median value of price predicted",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, main_app_predictions_bucket)",
     "legendFormat": "Median price predicted (in rub)"
    }
   ]
  },
  {
   "title": "Total Number of Predictions Made",
   "type": "stat",
   "description": "Total number of predictions since the service started",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(predictions_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Prediction Latency (in Seconds)",
   "type": "gauge",
   "description": "Average latency per request in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(prediction_latency_seconds_sum[5m])) / sum(rate(prediction_latency_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predictions Number Increase over 1 Minute",
   "type": "timeseries",
   "description": "Change of predictions number over 1 minute time interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(predictions_total[1m])",
     "legendFormat": "Change of prediction number made over 1 minute"
    }
   ]
  },
  {
   "title": "Prediction Latency Distribution",
   "type": "histogram",
   "description": "Requests distribution across latency buckets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(prediction_latency_seconds_bucket[1m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Error Rate per 1 Minute ",
   "type": "timeseries",
   "description": "Number of failed requests with client errors (HTTP error 400–499) or server errors (HTTP error 500–599) in 1 minute to total number of requests in 1 minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..|5..\"}[1m])) by (status)",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Average HTTP Request Latency",
   "type": "timeseries",
   "description": "Average request latency in seconds per 1 minute time interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) / sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Average request latency over 1 minute (in seconds)"
    }
   ]
  }
 ]
}